# Generated by Django 3.2 on 2021-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('addrress', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11)),
            ],
        ),
    ]
