# Generated by Django 3.2 on 2021-04-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('adddress', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.position')),
            ],
        ),
    ]
